name = "github"

[style]
display-name = "GitHub"
background-color = "#24292e"
background-color-hover = "#2f363c"

[url]
auth = "https://github.com/login/oauth/authorize"
token = "https://github.com/login/oauth/access_token"
