name = "discord"

[style]
display-name = "Discord"
background-color = "#5865f2"
background-color-hover = "#707bf4"

[url]
auth = "https://discord.com/api/oauth2/authorize"
token = "https://discord.com/api/oauth2/token"
